# Global Food Database - Comprehensive food items from every cuisine
# Format: name, calories, protein, carbs, fats, serving, category, is_veg, price_inr, cuisine

GLOBAL_FOOD_DATABASE = [
    # ===== INDIAN - North Indian =====
    {"name": "Roti/Chapati", "calories": 120, "protein": 3, "carbs": 20, "fats": 3.5, "serving": "1 pc (40g)", "category": "grain", "is_veg": True, "price_inr": 3, "cuisine": "indian"},
    {"name": "Paratha (plain)", "calories": 180, "protein": 4, "carbs": 28, "fats": 6, "serving": "1 pc", "category": "grain", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Naan", "calories": 260, "protein": 9, "carbs": 45, "fats": 5, "serving": "1 pc (90g)", "category": "grain", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Aloo Paratha", "calories": 230, "protein": 5, "carbs": 34, "fats": 9, "serving": "1 pc", "category": "grain", "is_veg": True, "price_inr": 12, "cuisine": "indian"},
    {"name": "Paneer Butter Masala", "calories": 320, "protein": 14, "carbs": 12, "fats": 24, "serving": "150g", "category": "curry", "is_veg": True, "price_inr": 40, "cuisine": "indian"},
    {"name": "Palak Paneer", "calories": 210, "protein": 12, "carbs": 8, "fats": 15, "serving": "150g", "category": "curry", "is_veg": True, "price_inr": 30, "cuisine": "indian"},
    {"name": "Paneer Bhurji", "calories": 280, "protein": 20, "carbs": 5, "fats": 20, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 35, "cuisine": "indian"},
    {"name": "Paneer Tikka", "calories": 250, "protein": 18, "carbs": 8, "fats": 17, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 40, "cuisine": "indian"},
    {"name": "Dal Masoor", "calories": 174, "protein": 13, "carbs": 28, "fats": 1, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 10, "cuisine": "indian"},
    {"name": "Dal Moong", "calories": 160, "protein": 12, "carbs": 26, "fats": 0.8, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 10, "cuisine": "indian"},
    {"name": "Dal Toor", "calories": 180, "protein": 14, "carbs": 30, "fats": 1.2, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 12, "cuisine": "indian"},
    {"name": "Dal Makhani", "calories": 230, "protein": 10, "carbs": 26, "fats": 10, "serving": "150g", "category": "curry", "is_veg": True, "price_inr": 20, "cuisine": "indian"},
    {"name": "Rajma (cooked)", "calories": 190, "protein": 13, "carbs": 33, "fats": 1, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 12, "cuisine": "indian"},
    {"name": "Chole/Chana (cooked)", "calories": 246, "protein": 13, "carbs": 40, "fats": 4, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 12, "cuisine": "indian"},
    {"name": "Aloo Gobi", "calories": 120, "protein": 3, "carbs": 18, "fats": 5, "serving": "150g", "category": "curry", "is_veg": True, "price_inr": 12, "cuisine": "indian"},
    {"name": "Bhindi Masala", "calories": 90, "protein": 3, "carbs": 10, "fats": 5, "serving": "150g", "category": "curry", "is_veg": True, "price_inr": 12, "cuisine": "indian"},
    {"name": "Matar Paneer", "calories": 260, "protein": 14, "carbs": 14, "fats": 18, "serving": "150g", "category": "curry", "is_veg": True, "price_inr": 30, "cuisine": "indian"},
    {"name": "Curd/Yogurt", "calories": 90, "protein": 5, "carbs": 7, "fats": 5, "serving": "150g", "category": "dairy", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Raita", "calories": 50, "protein": 2, "carbs": 5, "fats": 2.5, "serving": "100g", "category": "side", "is_veg": True, "price_inr": 5, "cuisine": "indian"},
    {"name": "Butter Chicken", "calories": 290, "protein": 25, "carbs": 10, "fats": 18, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 40, "cuisine": "indian"},
    {"name": "Chicken Tikka", "calories": 180, "protein": 28, "carbs": 4, "fats": 6, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 35, "cuisine": "indian"},
    {"name": "Chicken Biryani", "calories": 350, "protein": 18, "carbs": 45, "fats": 12, "serving": "250g", "category": "meal", "is_veg": False, "price_inr": 50, "cuisine": "indian"},
    {"name": "Mutton Curry", "calories": 300, "protein": 24, "carbs": 8, "fats": 20, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 60, "cuisine": "indian"},
    {"name": "Tandoori Chicken", "calories": 200, "protein": 30, "carbs": 5, "fats": 8, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 45, "cuisine": "indian"},
    {"name": "Keema Matar", "calories": 250, "protein": 22, "carbs": 10, "fats": 14, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 45, "cuisine": "indian"},
    {"name": "Fish Curry", "calories": 200, "protein": 24, "carbs": 5, "fats": 10, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 35, "cuisine": "indian"},
    # ===== INDIAN - South Indian =====
    {"name": "Idli", "calories": 58, "protein": 2, "carbs": 12, "fats": 0.2, "serving": "1 pc (60g)", "category": "breakfast", "is_veg": True, "price_inr": 5, "cuisine": "indian"},
    {"name": "Dosa (plain)", "calories": 120, "protein": 3, "carbs": 18, "fats": 4, "serving": "1 pc", "category": "breakfast", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Masala Dosa", "calories": 210, "protein": 5, "carbs": 32, "fats": 7, "serving": "1 pc", "category": "breakfast", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Sambar", "calories": 85, "protein": 4, "carbs": 14, "fats": 2, "serving": "150g", "category": "curry", "is_veg": True, "price_inr": 10, "cuisine": "indian"},
    {"name": "Rasam", "calories": 40, "protein": 2, "carbs": 6, "fats": 1, "serving": "150ml", "category": "soup", "is_veg": True, "price_inr": 5, "cuisine": "indian"},
    {"name": "Curd Rice", "calories": 180, "protein": 5, "carbs": 32, "fats": 4, "serving": "200g", "category": "meal", "is_veg": True, "price_inr": 10, "cuisine": "indian"},
    {"name": "Lemon Rice", "calories": 200, "protein": 4, "carbs": 38, "fats": 4, "serving": "200g", "category": "meal", "is_veg": True, "price_inr": 10, "cuisine": "indian"},
    {"name": "Coconut Chutney", "calories": 80, "protein": 1.5, "carbs": 4, "fats": 7, "serving": "30g", "category": "side", "is_veg": True, "price_inr": 5, "cuisine": "indian"},
    {"name": "Uttapam", "calories": 160, "protein": 5, "carbs": 26, "fats": 4, "serving": "1 pc", "category": "breakfast", "is_veg": True, "price_inr": 12, "cuisine": "indian"},
    {"name": "Appam", "calories": 120, "protein": 2, "carbs": 22, "fats": 2, "serving": "1 pc", "category": "breakfast", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Vada", "calories": 150, "protein": 6, "carbs": 14, "fats": 8, "serving": "1 pc", "category": "snack", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Pesarattu", "calories": 130, "protein": 7, "carbs": 18, "fats": 3, "serving": "1 pc", "category": "breakfast", "is_veg": True, "price_inr": 10, "cuisine": "indian"},
    # ===== INDIAN - Common Staples =====
    {"name": "Rice (cooked)", "calories": 195, "protein": 4, "carbs": 45, "fats": 0.5, "serving": "150g", "category": "grain", "is_veg": True, "price_inr": 5, "cuisine": "indian"},
    {"name": "Brown Rice (cooked)", "calories": 175, "protein": 4.5, "carbs": 38, "fats": 1.5, "serving": "150g", "category": "grain", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Paneer", "calories": 265, "protein": 18, "carbs": 1.2, "fats": 21, "serving": "100g", "category": "protein", "is_veg": True, "price_inr": 35, "cuisine": "indian"},
    {"name": "Egg (boiled)", "calories": 78, "protein": 6, "carbs": 0.6, "fats": 5, "serving": "1 pc (50g)", "category": "protein", "is_veg": False, "price_inr": 7, "cuisine": "indian"},
    {"name": "Egg Bhurji", "calories": 200, "protein": 14, "carbs": 4, "fats": 15, "serving": "2 eggs", "category": "protein", "is_veg": False, "price_inr": 15, "cuisine": "indian"},
    {"name": "Chicken Breast", "calories": 165, "protein": 31, "carbs": 0, "fats": 3.6, "serving": "100g", "category": "protein", "is_veg": False, "price_inr": 25, "cuisine": "indian"},
    {"name": "Chicken Curry", "calories": 220, "protein": 22, "carbs": 8, "fats": 12, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 30, "cuisine": "indian"},
    {"name": "Soya Chunks", "calories": 173, "protein": 26, "carbs": 16, "fats": 0.5, "serving": "50g dry", "category": "protein", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Milk (full cream)", "calories": 150, "protein": 8, "carbs": 12, "fats": 8, "serving": "250ml", "category": "dairy", "is_veg": True, "price_inr": 14, "cuisine": "indian"},
    {"name": "Poha", "calories": 130, "protein": 3, "carbs": 27, "fats": 2, "serving": "100g cooked", "category": "breakfast", "is_veg": True, "price_inr": 5, "cuisine": "indian"},
    {"name": "Upma", "calories": 143, "protein": 4, "carbs": 24, "fats": 4, "serving": "150g", "category": "breakfast", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Khichdi", "calories": 200, "protein": 8, "carbs": 34, "fats": 4, "serving": "200g", "category": "meal", "is_veg": True, "price_inr": 10, "cuisine": "indian"},
    {"name": "Pav Bhaji", "calories": 350, "protein": 8, "carbs": 45, "fats": 16, "serving": "1 plate", "category": "meal", "is_veg": True, "price_inr": 30, "cuisine": "indian"},
    {"name": "Veg Pulao", "calories": 220, "protein": 5, "carbs": 40, "fats": 5, "serving": "200g", "category": "meal", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    # ===== INDIAN - Snacks & Street Food =====
    {"name": "Samosa", "calories": 260, "protein": 5, "carbs": 28, "fats": 15, "serving": "1 pc (80g)", "category": "snack", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Pani Puri/Golgappa", "calories": 180, "protein": 3, "carbs": 30, "fats": 6, "serving": "6 pcs", "category": "snack", "is_veg": True, "price_inr": 20, "cuisine": "indian"},
    {"name": "Bhel Puri", "calories": 200, "protein": 5, "carbs": 34, "fats": 6, "serving": "1 plate", "category": "snack", "is_veg": True, "price_inr": 20, "cuisine": "indian"},
    {"name": "Roasted Chana", "calories": 180, "protein": 10, "carbs": 28, "fats": 4, "serving": "50g", "category": "snack", "is_veg": True, "price_inr": 5, "cuisine": "indian"},
    {"name": "Sprouts (mixed)", "calories": 100, "protein": 7, "carbs": 16, "fats": 0.5, "serving": "100g", "category": "snack", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Dhokla", "calories": 130, "protein": 5, "carbs": 22, "fats": 3, "serving": "3 pcs", "category": "snack", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Kachori", "calories": 280, "protein": 5, "carbs": 28, "fats": 16, "serving": "1 pc", "category": "snack", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Pakora/Bhajiya", "calories": 220, "protein": 4, "carbs": 18, "fats": 15, "serving": "5 pcs", "category": "snack", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Aloo Tikki", "calories": 160, "protein": 3, "carbs": 22, "fats": 7, "serving": "1 pc", "category": "snack", "is_veg": True, "price_inr": 10, "cuisine": "indian"},
    # ===== INDIAN - Sweets & Desserts =====
    {"name": "Gulab Jamun", "calories": 150, "protein": 2, "carbs": 22, "fats": 6, "serving": "1 pc", "category": "dessert", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Rasgulla", "calories": 120, "protein": 3, "carbs": 24, "fats": 1, "serving": "1 pc", "category": "dessert", "is_veg": True, "price_inr": 12, "cuisine": "indian"},
    {"name": "Jalebi", "calories": 150, "protein": 1, "carbs": 30, "fats": 4, "serving": "2 pcs", "category": "dessert", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Kheer", "calories": 200, "protein": 5, "carbs": 32, "fats": 6, "serving": "150g", "category": "dessert", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Halwa (Sooji)", "calories": 250, "protein": 4, "carbs": 35, "fats": 12, "serving": "100g", "category": "dessert", "is_veg": True, "price_inr": 12, "cuisine": "indian"},
    # ===== CHINESE =====
    {"name": "Fried Rice", "calories": 280, "protein": 6, "carbs": 42, "fats": 10, "serving": "200g", "category": "meal", "is_veg": True, "price_inr": 35, "cuisine": "chinese"},
    {"name": "Chicken Fried Rice", "calories": 320, "protein": 14, "carbs": 42, "fats": 12, "serving": "200g", "category": "meal", "is_veg": False, "price_inr": 45, "cuisine": "chinese"},
    {"name": "Hakka Noodles", "calories": 300, "protein": 7, "carbs": 45, "fats": 10, "serving": "200g", "category": "meal", "is_veg": True, "price_inr": 35, "cuisine": "chinese"},
    {"name": "Chicken Noodles", "calories": 340, "protein": 15, "carbs": 45, "fats": 12, "serving": "200g", "category": "meal", "is_veg": False, "price_inr": 50, "cuisine": "chinese"},
    {"name": "Manchurian (dry)", "calories": 250, "protein": 5, "carbs": 28, "fats": 14, "serving": "150g", "category": "snack", "is_veg": True, "price_inr": 30, "cuisine": "chinese"},
    {"name": "Chicken Manchurian", "calories": 280, "protein": 18, "carbs": 20, "fats": 14, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 45, "cuisine": "chinese"},
    {"name": "Spring Roll", "calories": 130, "protein": 3, "carbs": 18, "fats": 5, "serving": "1 pc", "category": "snack", "is_veg": True, "price_inr": 15, "cuisine": "chinese"},
    {"name": "Sweet and Sour Chicken", "calories": 300, "protein": 20, "carbs": 30, "fats": 12, "serving": "200g", "category": "protein", "is_veg": False, "price_inr": 50, "cuisine": "chinese"},
    {"name": "Hot and Sour Soup", "calories": 90, "protein": 5, "carbs": 12, "fats": 3, "serving": "200ml", "category": "soup", "is_veg": False, "price_inr": 20, "cuisine": "chinese"},
    {"name": "Dim Sum (steamed)", "calories": 160, "protein": 8, "carbs": 20, "fats": 5, "serving": "4 pcs", "category": "snack", "is_veg": False, "price_inr": 40, "cuisine": "chinese"},
    {"name": "Kung Pao Chicken", "calories": 280, "protein": 22, "carbs": 14, "fats": 16, "serving": "200g", "category": "protein", "is_veg": False, "price_inr": 55, "cuisine": "chinese"},
    {"name": "Mapo Tofu", "calories": 190, "protein": 12, "carbs": 10, "fats": 12, "serving": "200g", "category": "protein", "is_veg": True, "price_inr": 35, "cuisine": "chinese"},
    {"name": "Congee/Rice Porridge", "calories": 120, "protein": 3, "carbs": 22, "fats": 2, "serving": "250g", "category": "breakfast", "is_veg": True, "price_inr": 15, "cuisine": "chinese"},
    {"name": "Wonton Soup", "calories": 180, "protein": 10, "carbs": 22, "fats": 6, "serving": "250ml", "category": "soup", "is_veg": False, "price_inr": 35, "cuisine": "chinese"},
    # ===== JAPANESE =====
    {"name": "Sushi Roll (California)", "calories": 250, "protein": 9, "carbs": 38, "fats": 7, "serving": "6 pcs", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "japanese"},
    {"name": "Ramen", "calories": 400, "protein": 18, "carbs": 52, "fats": 14, "serving": "1 bowl (400ml)", "category": "meal", "is_veg": False, "price_inr": 100, "cuisine": "japanese"},
    {"name": "Miso Soup", "calories": 60, "protein": 4, "carbs": 6, "fats": 2, "serving": "200ml", "category": "soup", "is_veg": True, "price_inr": 30, "cuisine": "japanese"},
    {"name": "Edamame", "calories": 120, "protein": 11, "carbs": 9, "fats": 5, "serving": "100g", "category": "snack", "is_veg": True, "price_inr": 40, "cuisine": "japanese"},
    {"name": "Teriyaki Chicken", "calories": 230, "protein": 26, "carbs": 12, "fats": 8, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 70, "cuisine": "japanese"},
    {"name": "Tempura (mixed)", "calories": 300, "protein": 8, "carbs": 28, "fats": 18, "serving": "5 pcs", "category": "snack", "is_veg": True, "price_inr": 60, "cuisine": "japanese"},
    {"name": "Onigiri", "calories": 180, "protein": 5, "carbs": 35, "fats": 2, "serving": "1 pc (120g)", "category": "snack", "is_veg": False, "price_inr": 40, "cuisine": "japanese"},
    {"name": "Katsu Curry", "calories": 500, "protein": 25, "carbs": 55, "fats": 20, "serving": "1 plate", "category": "meal", "is_veg": False, "price_inr": 120, "cuisine": "japanese"},
    {"name": "Gyoza (Pan-fried)", "calories": 200, "protein": 10, "carbs": 22, "fats": 8, "serving": "5 pcs", "category": "snack", "is_veg": False, "price_inr": 50, "cuisine": "japanese"},
    {"name": "Tofu (firm)", "calories": 80, "protein": 9, "carbs": 2, "fats": 4.5, "serving": "100g", "category": "protein", "is_veg": True, "price_inr": 25, "cuisine": "japanese"},
    # ===== KOREAN =====
    {"name": "Bibimbap", "calories": 450, "protein": 20, "carbs": 58, "fats": 16, "serving": "1 bowl", "category": "meal", "is_veg": False, "price_inr": 100, "cuisine": "korean"},
    {"name": "Kimchi", "calories": 23, "protein": 1.3, "carbs": 4, "fats": 0.2, "serving": "100g", "category": "side", "is_veg": True, "price_inr": 20, "cuisine": "korean"},
    {"name": "Bulgogi", "calories": 260, "protein": 25, "carbs": 12, "fats": 12, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 80, "cuisine": "korean"},
    {"name": "Korean Fried Chicken", "calories": 350, "protein": 22, "carbs": 20, "fats": 20, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 80, "cuisine": "korean"},
    {"name": "Japchae", "calories": 230, "protein": 6, "carbs": 38, "fats": 7, "serving": "200g", "category": "meal", "is_veg": True, "price_inr": 50, "cuisine": "korean"},
    {"name": "Tteokbokki", "calories": 280, "protein": 5, "carbs": 48, "fats": 8, "serving": "200g", "category": "snack", "is_veg": True, "price_inr": 50, "cuisine": "korean"},
    {"name": "Kimbap", "calories": 300, "protein": 10, "carbs": 42, "fats": 10, "serving": "1 roll (6 pcs)", "category": "meal", "is_veg": False, "price_inr": 60, "cuisine": "korean"},
    # ===== THAI =====
    {"name": "Pad Thai", "calories": 400, "protein": 16, "carbs": 50, "fats": 16, "serving": "300g", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "thai"},
    {"name": "Green Curry (chicken)", "calories": 300, "protein": 20, "carbs": 12, "fats": 20, "serving": "200g", "category": "curry", "is_veg": False, "price_inr": 70, "cuisine": "thai"},
    {"name": "Tom Yum Soup", "calories": 120, "protein": 12, "carbs": 8, "fats": 4, "serving": "250ml", "category": "soup", "is_veg": False, "price_inr": 60, "cuisine": "thai"},
    {"name": "Thai Fried Rice", "calories": 320, "protein": 14, "carbs": 42, "fats": 12, "serving": "250g", "category": "meal", "is_veg": False, "price_inr": 60, "cuisine": "thai"},
    {"name": "Mango Sticky Rice", "calories": 350, "protein": 4, "carbs": 65, "fats": 10, "serving": "200g", "category": "dessert", "is_veg": True, "price_inr": 50, "cuisine": "thai"},
    {"name": "Som Tum (Papaya Salad)", "calories": 120, "protein": 3, "carbs": 18, "fats": 5, "serving": "150g", "category": "side", "is_veg": True, "price_inr": 40, "cuisine": "thai"},
    {"name": "Massaman Curry", "calories": 350, "protein": 22, "carbs": 18, "fats": 22, "serving": "200g", "category": "curry", "is_veg": False, "price_inr": 80, "cuisine": "thai"},
    # ===== ITALIAN =====
    {"name": "Margherita Pizza (1 slice)", "calories": 250, "protein": 10, "carbs": 30, "fats": 10, "serving": "1 slice (130g)", "category": "meal", "is_veg": True, "price_inr": 40, "cuisine": "italian"},
    {"name": "Pasta Arrabiata", "calories": 350, "protein": 10, "carbs": 55, "fats": 10, "serving": "250g", "category": "meal", "is_veg": True, "price_inr": 45, "cuisine": "italian"},
    {"name": "Pasta Alfredo", "calories": 450, "protein": 14, "carbs": 50, "fats": 22, "serving": "250g", "category": "meal", "is_veg": True, "price_inr": 55, "cuisine": "italian"},
    {"name": "Spaghetti Bolognese", "calories": 400, "protein": 20, "carbs": 50, "fats": 14, "serving": "300g", "category": "meal", "is_veg": False, "price_inr": 60, "cuisine": "italian"},
    {"name": "Bruschetta", "calories": 170, "protein": 4, "carbs": 22, "fats": 8, "serving": "3 pcs", "category": "snack", "is_veg": True, "price_inr": 30, "cuisine": "italian"},
    {"name": "Minestrone Soup", "calories": 120, "protein": 5, "carbs": 18, "fats": 3, "serving": "250ml", "category": "soup", "is_veg": True, "price_inr": 30, "cuisine": "italian"},
    {"name": "Lasagna", "calories": 380, "protein": 18, "carbs": 35, "fats": 18, "serving": "250g", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "italian"},
    {"name": "Risotto", "calories": 350, "protein": 10, "carbs": 50, "fats": 12, "serving": "250g", "category": "meal", "is_veg": True, "price_inr": 60, "cuisine": "italian"},
    {"name": "Tiramisu", "calories": 300, "protein": 5, "carbs": 35, "fats": 16, "serving": "1 slice", "category": "dessert", "is_veg": True, "price_inr": 80, "cuisine": "italian"},
    {"name": "Penne Pasta", "calories": 220, "protein": 8, "carbs": 42, "fats": 2, "serving": "100g dry", "category": "grain", "is_veg": True, "price_inr": 15, "cuisine": "italian"},
    # ===== MEXICAN =====
    {"name": "Burrito (chicken)", "calories": 500, "protein": 25, "carbs": 55, "fats": 20, "serving": "1 pc (300g)", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "mexican"},
    {"name": "Tacos (chicken)", "calories": 200, "protein": 12, "carbs": 18, "fats": 9, "serving": "1 pc", "category": "meal", "is_veg": False, "price_inr": 40, "cuisine": "mexican"},
    {"name": "Quesadilla", "calories": 350, "protein": 16, "carbs": 30, "fats": 18, "serving": "1 pc", "category": "meal", "is_veg": False, "price_inr": 50, "cuisine": "mexican"},
    {"name": "Nachos with Cheese", "calories": 400, "protein": 10, "carbs": 42, "fats": 22, "serving": "150g", "category": "snack", "is_veg": True, "price_inr": 50, "cuisine": "mexican"},
    {"name": "Guacamole", "calories": 160, "protein": 2, "carbs": 8, "fats": 14, "serving": "100g", "category": "side", "is_veg": True, "price_inr": 40, "cuisine": "mexican"},
    {"name": "Enchilada", "calories": 280, "protein": 14, "carbs": 24, "fats": 14, "serving": "1 pc", "category": "meal", "is_veg": False, "price_inr": 50, "cuisine": "mexican"},
    {"name": "Churros", "calories": 240, "protein": 3, "carbs": 30, "fats": 12, "serving": "3 pcs", "category": "dessert", "is_veg": True, "price_inr": 40, "cuisine": "mexican"},
    {"name": "Mexican Rice", "calories": 210, "protein": 4, "carbs": 40, "fats": 4, "serving": "200g", "category": "side", "is_veg": True, "price_inr": 20, "cuisine": "mexican"},
    # ===== AMERICAN / FAST FOOD =====
    {"name": "Hamburger", "calories": 450, "protein": 25, "carbs": 35, "fats": 24, "serving": "1 pc", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "american"},
    {"name": "Cheeseburger", "calories": 520, "protein": 28, "carbs": 38, "fats": 28, "serving": "1 pc", "category": "meal", "is_veg": False, "price_inr": 100, "cuisine": "american"},
    {"name": "Hot Dog", "calories": 300, "protein": 10, "carbs": 25, "fats": 18, "serving": "1 pc", "category": "meal", "is_veg": False, "price_inr": 50, "cuisine": "american"},
    {"name": "French Fries", "calories": 320, "protein": 4, "carbs": 40, "fats": 16, "serving": "medium (120g)", "category": "side", "is_veg": True, "price_inr": 30, "cuisine": "american"},
    {"name": "Fried Chicken (KFC-style)", "calories": 280, "protein": 22, "carbs": 12, "fats": 18, "serving": "1 pc (100g)", "category": "protein", "is_veg": False, "price_inr": 60, "cuisine": "american"},
    {"name": "Chicken Nuggets", "calories": 280, "protein": 14, "carbs": 18, "fats": 18, "serving": "6 pcs (100g)", "category": "snack", "is_veg": False, "price_inr": 50, "cuisine": "american"},
    {"name": "Grilled Chicken Sandwich", "calories": 350, "protein": 28, "carbs": 32, "fats": 12, "serving": "1 pc", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "american"},
    {"name": "Caesar Salad", "calories": 200, "protein": 8, "carbs": 12, "fats": 14, "serving": "200g", "category": "side", "is_veg": True, "price_inr": 60, "cuisine": "american"},
    {"name": "Mac and Cheese", "calories": 380, "protein": 14, "carbs": 40, "fats": 18, "serving": "250g", "category": "meal", "is_veg": True, "price_inr": 60, "cuisine": "american"},
    {"name": "Pancakes", "calories": 280, "protein": 8, "carbs": 42, "fats": 10, "serving": "3 pcs", "category": "breakfast", "is_veg": True, "price_inr": 50, "cuisine": "american"},
    {"name": "Bacon Strips", "calories": 160, "protein": 12, "carbs": 0, "fats": 12, "serving": "3 strips", "category": "protein", "is_veg": False, "price_inr": 40, "cuisine": "american"},
    {"name": "BBQ Ribs", "calories": 350, "protein": 25, "carbs": 15, "fats": 22, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 120, "cuisine": "american"},
    {"name": "Coleslaw", "calories": 150, "protein": 1, "carbs": 12, "fats": 11, "serving": "150g", "category": "side", "is_veg": True, "price_inr": 20, "cuisine": "american"},
    {"name": "Onion Rings", "calories": 280, "protein": 4, "carbs": 32, "fats": 16, "serving": "8 pcs", "category": "snack", "is_veg": True, "price_inr": 40, "cuisine": "american"},
    # ===== MEDITERRANEAN / MIDDLE EASTERN =====
    {"name": "Hummus", "calories": 170, "protein": 8, "carbs": 14, "fats": 10, "serving": "100g", "category": "side", "is_veg": True, "price_inr": 40, "cuisine": "mediterranean"},
    {"name": "Falafel", "calories": 330, "protein": 13, "carbs": 32, "fats": 18, "serving": "6 pcs (100g)", "category": "snack", "is_veg": True, "price_inr": 40, "cuisine": "mediterranean"},
    {"name": "Shawarma (chicken)", "calories": 400, "protein": 28, "carbs": 35, "fats": 16, "serving": "1 wrap", "category": "meal", "is_veg": False, "price_inr": 70, "cuisine": "mediterranean"},
    {"name": "Greek Salad", "calories": 150, "protein": 5, "carbs": 10, "fats": 10, "serving": "200g", "category": "side", "is_veg": True, "price_inr": 50, "cuisine": "mediterranean"},
    {"name": "Pita Bread", "calories": 160, "protein": 6, "carbs": 30, "fats": 2, "serving": "1 pc (60g)", "category": "grain", "is_veg": True, "price_inr": 15, "cuisine": "mediterranean"},
    {"name": "Kebab (lamb)", "calories": 280, "protein": 24, "carbs": 6, "fats": 18, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 80, "cuisine": "mediterranean"},
    {"name": "Baba Ganoush", "calories": 130, "protein": 3, "carbs": 12, "fats": 8, "serving": "100g", "category": "side", "is_veg": True, "price_inr": 35, "cuisine": "mediterranean"},
    {"name": "Tabbouleh", "calories": 120, "protein": 3, "carbs": 16, "fats": 6, "serving": "150g", "category": "side", "is_veg": True, "price_inr": 30, "cuisine": "mediterranean"},
    {"name": "Baklava", "calories": 250, "protein": 4, "carbs": 30, "fats": 14, "serving": "1 pc (60g)", "category": "dessert", "is_veg": True, "price_inr": 50, "cuisine": "mediterranean"},
    {"name": "Doner Kebab", "calories": 450, "protein": 30, "carbs": 35, "fats": 20, "serving": "1 wrap", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "mediterranean"},
    # ===== SOUTHEAST ASIAN =====
    {"name": "Pho (Vietnamese)", "calories": 350, "protein": 20, "carbs": 45, "fats": 8, "serving": "1 bowl", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "southeast_asian"},
    {"name": "Banh Mi", "calories": 380, "protein": 18, "carbs": 42, "fats": 14, "serving": "1 sandwich", "category": "meal", "is_veg": False, "price_inr": 60, "cuisine": "southeast_asian"},
    {"name": "Nasi Goreng", "calories": 400, "protein": 16, "carbs": 50, "fats": 16, "serving": "300g", "category": "meal", "is_veg": False, "price_inr": 60, "cuisine": "southeast_asian"},
    {"name": "Satay (chicken)", "calories": 250, "protein": 20, "carbs": 8, "fats": 16, "serving": "4 sticks", "category": "protein", "is_veg": False, "price_inr": 50, "cuisine": "southeast_asian"},
    {"name": "Laksa", "calories": 400, "protein": 18, "carbs": 40, "fats": 20, "serving": "1 bowl", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "southeast_asian"},
    {"name": "Gado-Gado", "calories": 250, "protein": 10, "carbs": 22, "fats": 14, "serving": "200g", "category": "side", "is_veg": True, "price_inr": 40, "cuisine": "southeast_asian"},
    # ===== CONTINENTAL / EUROPEAN =====
    {"name": "Croissant", "calories": 230, "protein": 5, "carbs": 26, "fats": 12, "serving": "1 pc (60g)", "category": "breakfast", "is_veg": True, "price_inr": 30, "cuisine": "european"},
    {"name": "Fish and Chips", "calories": 500, "protein": 22, "carbs": 48, "fats": 24, "serving": "300g", "category": "meal", "is_veg": False, "price_inr": 100, "cuisine": "european"},
    {"name": "Quiche Lorraine", "calories": 350, "protein": 14, "carbs": 22, "fats": 24, "serving": "1 slice (150g)", "category": "meal", "is_veg": False, "price_inr": 70, "cuisine": "european"},
    {"name": "Crepes (sweet)", "calories": 200, "protein": 5, "carbs": 30, "fats": 7, "serving": "1 pc", "category": "dessert", "is_veg": True, "price_inr": 40, "cuisine": "european"},
    {"name": "French Onion Soup", "calories": 220, "protein": 8, "carbs": 22, "fats": 12, "serving": "250ml", "category": "soup", "is_veg": True, "price_inr": 50, "cuisine": "european"},
    {"name": "Steak (grilled)", "calories": 300, "protein": 35, "carbs": 0, "fats": 18, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 150, "cuisine": "european"},
    {"name": "Shepherd's Pie", "calories": 350, "protein": 16, "carbs": 32, "fats": 18, "serving": "250g", "category": "meal", "is_veg": False, "price_inr": 80, "cuisine": "european"},
    {"name": "Baguette", "calories": 250, "protein": 8, "carbs": 48, "fats": 2, "serving": "1/3 stick (100g)", "category": "grain", "is_veg": True, "price_inr": 20, "cuisine": "european"},
    # ===== GLOBAL BASICS & STAPLES =====
    {"name": "Oats", "calories": 156, "protein": 7, "carbs": 27, "fats": 3, "serving": "40g dry", "category": "breakfast", "is_veg": True, "price_inr": 6, "cuisine": "global"},
    {"name": "Banana", "calories": 105, "protein": 1.3, "carbs": 27, "fats": 0.3, "serving": "1 medium", "category": "fruit", "is_veg": True, "price_inr": 5, "cuisine": "global"},
    {"name": "Apple", "calories": 95, "protein": 0.5, "carbs": 25, "fats": 0.3, "serving": "1 medium", "category": "fruit", "is_veg": True, "price_inr": 15, "cuisine": "global"},
    {"name": "Orange", "calories": 62, "protein": 1.2, "carbs": 15, "fats": 0.2, "serving": "1 medium", "category": "fruit", "is_veg": True, "price_inr": 10, "cuisine": "global"},
    {"name": "Mango", "calories": 135, "protein": 1.5, "carbs": 35, "fats": 0.5, "serving": "1 medium", "category": "fruit", "is_veg": True, "price_inr": 20, "cuisine": "global"},
    {"name": "Watermelon", "calories": 85, "protein": 1.7, "carbs": 21, "fats": 0.4, "serving": "300g", "category": "fruit", "is_veg": True, "price_inr": 10, "cuisine": "global"},
    {"name": "Grapes", "calories": 104, "protein": 1, "carbs": 27, "fats": 0.2, "serving": "150g", "category": "fruit", "is_veg": True, "price_inr": 15, "cuisine": "global"},
    {"name": "Peanut Butter", "calories": 188, "protein": 8, "carbs": 6, "fats": 16, "serving": "2 tbsp (32g)", "category": "snack", "is_veg": True, "price_inr": 15, "cuisine": "global"},
    {"name": "Almonds", "calories": 164, "protein": 6, "carbs": 6, "fats": 14, "serving": "28g (23 pcs)", "category": "snack", "is_veg": True, "price_inr": 20, "cuisine": "global"},
    {"name": "Walnuts", "calories": 185, "protein": 4.3, "carbs": 4, "fats": 18, "serving": "28g", "category": "snack", "is_veg": True, "price_inr": 25, "cuisine": "global"},
    {"name": "Cashews", "calories": 155, "protein": 5, "carbs": 9, "fats": 12, "serving": "28g", "category": "snack", "is_veg": True, "price_inr": 20, "cuisine": "global"},
    {"name": "Dates", "calories": 66, "protein": 0.4, "carbs": 18, "fats": 0, "serving": "2 pcs (24g)", "category": "fruit", "is_veg": True, "price_inr": 8, "cuisine": "global"},
    {"name": "Avocado", "calories": 160, "protein": 2, "carbs": 9, "fats": 15, "serving": "half (100g)", "category": "fruit", "is_veg": True, "price_inr": 50, "cuisine": "global"},
    {"name": "Sweet Potato", "calories": 115, "protein": 2, "carbs": 27, "fats": 0, "serving": "1 medium (130g)", "category": "grain", "is_veg": True, "price_inr": 8, "cuisine": "global"},
    {"name": "Quinoa (cooked)", "calories": 185, "protein": 7, "carbs": 32, "fats": 3, "serving": "150g", "category": "grain", "is_veg": True, "price_inr": 25, "cuisine": "global"},
    {"name": "Whole Wheat Bread", "calories": 130, "protein": 5, "carbs": 24, "fats": 2, "serving": "2 slices (60g)", "category": "grain", "is_veg": True, "price_inr": 8, "cuisine": "global"},
    {"name": "White Bread", "calories": 140, "protein": 4, "carbs": 26, "fats": 2, "serving": "2 slices (60g)", "category": "grain", "is_veg": True, "price_inr": 6, "cuisine": "global"},
    {"name": "Corn (boiled)", "calories": 130, "protein": 5, "carbs": 27, "fats": 2, "serving": "1 cob (150g)", "category": "grain", "is_veg": True, "price_inr": 10, "cuisine": "global"},
    # ===== PROTEIN SOURCES =====
    {"name": "Whey Protein", "calories": 120, "protein": 24, "carbs": 3, "fats": 1, "serving": "1 scoop (30g)", "category": "supplement", "is_veg": True, "price_inr": 30, "cuisine": "global"},
    {"name": "Greek Yogurt", "calories": 100, "protein": 10, "carbs": 6, "fats": 4, "serving": "150g", "category": "dairy", "is_veg": True, "price_inr": 25, "cuisine": "global"},
    {"name": "Cottage Cheese", "calories": 98, "protein": 11, "carbs": 3, "fats": 4, "serving": "100g", "category": "dairy", "is_veg": True, "price_inr": 20, "cuisine": "global"},
    {"name": "Tuna (canned)", "calories": 130, "protein": 28, "carbs": 0, "fats": 1.5, "serving": "100g", "category": "protein", "is_veg": False, "price_inr": 40, "cuisine": "global"},
    {"name": "Salmon (grilled)", "calories": 200, "protein": 25, "carbs": 0, "fats": 11, "serving": "100g", "category": "protein", "is_veg": False, "price_inr": 80, "cuisine": "global"},
    {"name": "Prawns/Shrimp", "calories": 100, "protein": 20, "carbs": 1, "fats": 1.5, "serving": "100g", "category": "protein", "is_veg": False, "price_inr": 45, "cuisine": "global"},
    {"name": "Turkey Breast", "calories": 135, "protein": 30, "carbs": 0, "fats": 1, "serving": "100g", "category": "protein", "is_veg": False, "price_inr": 50, "cuisine": "global"},
    {"name": "Lentils (cooked)", "calories": 165, "protein": 12, "carbs": 28, "fats": 0.5, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 8, "cuisine": "global"},
    {"name": "Chickpeas (cooked)", "calories": 180, "protein": 10, "carbs": 28, "fats": 3, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 10, "cuisine": "global"},
    {"name": "Black Beans (cooked)", "calories": 170, "protein": 11, "carbs": 30, "fats": 0.5, "serving": "150g", "category": "protein", "is_veg": True, "price_inr": 12, "cuisine": "global"},
    # ===== BEVERAGES =====
    {"name": "Masala Chai", "calories": 80, "protein": 2, "carbs": 12, "fats": 3, "serving": "150ml", "category": "beverage", "is_veg": True, "price_inr": 10, "cuisine": "indian"},
    {"name": "Black Coffee", "calories": 5, "protein": 0.3, "carbs": 1, "fats": 0, "serving": "200ml", "category": "beverage", "is_veg": True, "price_inr": 10, "cuisine": "global"},
    {"name": "Cappuccino", "calories": 120, "protein": 5, "carbs": 10, "fats": 6, "serving": "200ml", "category": "beverage", "is_veg": True, "price_inr": 30, "cuisine": "global"},
    {"name": "Lassi (sweet)", "calories": 180, "protein": 6, "carbs": 28, "fats": 5, "serving": "250ml", "category": "beverage", "is_veg": True, "price_inr": 15, "cuisine": "indian"},
    {"name": "Buttermilk/Chaas", "calories": 40, "protein": 2, "carbs": 5, "fats": 1, "serving": "250ml", "category": "beverage", "is_veg": True, "price_inr": 8, "cuisine": "indian"},
    {"name": "Coconut Water", "calories": 45, "protein": 1.7, "carbs": 9, "fats": 0.5, "serving": "250ml", "category": "beverage", "is_veg": True, "price_inr": 20, "cuisine": "global"},
    {"name": "Orange Juice", "calories": 110, "protein": 2, "carbs": 26, "fats": 0.5, "serving": "250ml", "category": "beverage", "is_veg": True, "price_inr": 20, "cuisine": "global"},
    {"name": "Smoothie (banana)", "calories": 200, "protein": 6, "carbs": 35, "fats": 4, "serving": "300ml", "category": "beverage", "is_veg": True, "price_inr": 30, "cuisine": "global"},
    {"name": "Protein Shake", "calories": 220, "protein": 28, "carbs": 18, "fats": 4, "serving": "350ml", "category": "beverage", "is_veg": True, "price_inr": 40, "cuisine": "global"},
    {"name": "Green Tea", "calories": 2, "protein": 0, "carbs": 0.5, "fats": 0, "serving": "200ml", "category": "beverage", "is_veg": True, "price_inr": 10, "cuisine": "global"},
    # ===== GLOBAL DESSERTS =====
    {"name": "Chocolate Cake", "calories": 350, "protein": 5, "carbs": 45, "fats": 18, "serving": "1 slice (100g)", "category": "dessert", "is_veg": True, "price_inr": 50, "cuisine": "global"},
    {"name": "Ice Cream (vanilla)", "calories": 200, "protein": 3, "carbs": 24, "fats": 11, "serving": "1 scoop (100g)", "category": "dessert", "is_veg": True, "price_inr": 25, "cuisine": "global"},
    {"name": "Brownie", "calories": 280, "protein": 3, "carbs": 35, "fats": 15, "serving": "1 pc (60g)", "category": "dessert", "is_veg": True, "price_inr": 30, "cuisine": "global"},
    {"name": "Cheesecake", "calories": 320, "protein": 6, "carbs": 28, "fats": 22, "serving": "1 slice (100g)", "category": "dessert", "is_veg": True, "price_inr": 80, "cuisine": "global"},
    {"name": "Donut", "calories": 250, "protein": 3, "carbs": 30, "fats": 14, "serving": "1 pc", "category": "dessert", "is_veg": True, "price_inr": 30, "cuisine": "global"},
    {"name": "Muffin (blueberry)", "calories": 310, "protein": 5, "carbs": 42, "fats": 14, "serving": "1 pc", "category": "dessert", "is_veg": True, "price_inr": 40, "cuisine": "global"},
    # ===== GLOBAL SNACKS =====
    {"name": "Popcorn (plain)", "calories": 110, "protein": 3, "carbs": 20, "fats": 3, "serving": "30g", "category": "snack", "is_veg": True, "price_inr": 10, "cuisine": "global"},
    {"name": "Chips/Crisps", "calories": 260, "protein": 3, "carbs": 26, "fats": 17, "serving": "50g", "category": "snack", "is_veg": True, "price_inr": 20, "cuisine": "global"},
    {"name": "Granola Bar", "calories": 190, "protein": 4, "carbs": 28, "fats": 8, "serving": "1 bar (40g)", "category": "snack", "is_veg": True, "price_inr": 25, "cuisine": "global"},
    {"name": "Trail Mix", "calories": 175, "protein": 5, "carbs": 16, "fats": 11, "serving": "35g", "category": "snack", "is_veg": True, "price_inr": 20, "cuisine": "global"},
    {"name": "Dark Chocolate", "calories": 170, "protein": 2, "carbs": 13, "fats": 12, "serving": "30g", "category": "snack", "is_veg": True, "price_inr": 15, "cuisine": "global"},
    {"name": "Peanuts (roasted)", "calories": 165, "protein": 7, "carbs": 5, "fats": 14, "serving": "28g", "category": "snack", "is_veg": True, "price_inr": 8, "cuisine": "global"},
    {"name": "Energy Bar", "calories": 220, "protein": 10, "carbs": 30, "fats": 7, "serving": "1 bar (50g)", "category": "snack", "is_veg": True, "price_inr": 30, "cuisine": "global"},
    # ===== AFRICAN =====
    {"name": "Jollof Rice", "calories": 300, "protein": 6, "carbs": 50, "fats": 9, "serving": "250g", "category": "meal", "is_veg": True, "price_inr": 40, "cuisine": "african"},
    {"name": "Injera", "calories": 140, "protein": 4, "carbs": 28, "fats": 1, "serving": "1 pc (100g)", "category": "grain", "is_veg": True, "price_inr": 20, "cuisine": "african"},
    {"name": "Tagine (chicken)", "calories": 280, "protein": 22, "carbs": 18, "fats": 14, "serving": "250g", "category": "meal", "is_veg": False, "price_inr": 70, "cuisine": "african"},
    {"name": "Couscous", "calories": 176, "protein": 6, "carbs": 36, "fats": 0.3, "serving": "150g cooked", "category": "grain", "is_veg": True, "price_inr": 15, "cuisine": "african"},
    # ===== SOUTH AMERICAN =====
    {"name": "Acai Bowl", "calories": 350, "protein": 5, "carbs": 52, "fats": 14, "serving": "300g", "category": "breakfast", "is_veg": True, "price_inr": 80, "cuisine": "south_american"},
    {"name": "Empanada", "calories": 250, "protein": 8, "carbs": 22, "fats": 14, "serving": "1 pc", "category": "snack", "is_veg": False, "price_inr": 40, "cuisine": "south_american"},
    {"name": "Ceviche", "calories": 150, "protein": 20, "carbs": 10, "fats": 3, "serving": "150g", "category": "protein", "is_veg": False, "price_inr": 80, "cuisine": "south_american"},
    {"name": "Arepa", "calories": 200, "protein": 4, "carbs": 32, "fats": 6, "serving": "1 pc", "category": "grain", "is_veg": True, "price_inr": 25, "cuisine": "south_american"},
    # ===== VEGETABLES (COMMON) =====
    {"name": "Broccoli (steamed)", "calories": 55, "protein": 3.7, "carbs": 11, "fats": 0.6, "serving": "150g", "category": "vegetable", "is_veg": True, "price_inr": 15, "cuisine": "global"},
    {"name": "Spinach (cooked)", "calories": 40, "protein": 5, "carbs": 6, "fats": 0.5, "serving": "150g", "category": "vegetable", "is_veg": True, "price_inr": 10, "cuisine": "global"},
    {"name": "Carrot", "calories": 35, "protein": 0.8, "carbs": 8, "fats": 0.2, "serving": "1 medium (80g)", "category": "vegetable", "is_veg": True, "price_inr": 5, "cuisine": "global"},
    {"name": "Cucumber", "calories": 16, "protein": 0.7, "carbs": 3.6, "fats": 0.1, "serving": "1 medium (100g)", "category": "vegetable", "is_veg": True, "price_inr": 5, "cuisine": "global"},
    {"name": "Tomato", "calories": 22, "protein": 1, "carbs": 4.8, "fats": 0.2, "serving": "1 medium (120g)", "category": "vegetable", "is_veg": True, "price_inr": 5, "cuisine": "global"},
    {"name": "Mushrooms (cooked)", "calories": 35, "protein": 3, "carbs": 5, "fats": 0.5, "serving": "100g", "category": "vegetable", "is_veg": True, "price_inr": 20, "cuisine": "global"},
    {"name": "Mixed Salad", "calories": 40, "protein": 2, "carbs": 6, "fats": 1, "serving": "150g", "category": "vegetable", "is_veg": True, "price_inr": 15, "cuisine": "global"},
]
